function pathView(){rememberScreen('path');state.journeyStep=Math.max(state.journeyStep||1,2);save();let p=state.path||'أطبق',cfg=p==='أكتشف'?{icon:'🌱',intro:'نبني الأساس خطوة بخطوة، مع تلميحات وأمثلة واضحة.',title:'اكتشفي المراحل ثم ثبتي المفهوم',desc:'استكشفي النموذج أولًا، ثم نفّذي تدريب المطابقة الموجّه.',btn:'ابدئي تدريب أكتشف',fn:'discoverTask()'}:p==='أبتكر'?{icon:'💡',intro:'أنتِ جاهزة لمهمة أعلى: حللي موقفًا واقعيًا وابني قرارك.',title:'حللي موقفًا وصممي خطة',desc:'راجعي النموذج عند الحاجة، ثم نفّذي تحدي الابتكار دون تلميحات مباشرة.',btn:'ابدئي تحدي أبتكر',fn:'innovateTask()'}:{icon:'🎯',intro:'حوّلي معرفتك إلى قرار صحيح في مواقف تطبيقية.',title:'طبّقي المراحل على مواقف واقعية',desc:'راجعي النموذج، ثم اختاري المرحلة المناسبة لكل موقف.',btn:'ابدئي مهمة أطبق',fn:'applyTask()'};S.innerHTML=`${hud()}<section class='game-hero'><span class='pill'>🧭 المسار الذكي · ${cfg.icon} ${p}</span><h2>مهمة مسار «${p}»</h2><p>${cfg.intro}</p><div class='level-line'><span>المهمة 2/5</span><div class='level-track'><i style='width:40%'></i></div><span class='xp-pop'>تعلم تكيفي</span></div></section><div class='mission'><div class='mission-head'><div class='mission-icon'>${cfg.icon}</div><div><small>مهمتك المخصصة</small><h3>${cfg.title}</h3></div></div><p>${cfg.desc}</p></div>${model()}<div id='stageDetail' aria-live='polite'><div class='stage-sheet'><div class='stage-head'><div class='stage-icon'>👆</div><div><small>مرجعك التفاعلي</small><h3>اختاري إحدى المراحل</h3></div></div><p>يمكنكِ مراجعة معنى أي مرحلة ومثالها قبل بدء مهمتك.</p></div></div><button class='cta' onclick='${cfg.fn}'>${cfg.btn} ←</button>`}
let adaptiveIndex=0,adaptiveCorrect=0;
const discoverQs=[['نفهم المشكلة واحتياجات المستخدم.',['التحليل','التنفيذ'],'التحليل'],['نرسم شكل الواجهات قبل البرمجة.',['الصيانة','التصميم'],'التصميم'],['نجرب النظام لاكتشاف الأخطاء.',['الاختبار','التوثيق'],'الاختبار']];
function discoverTask(){adaptiveIndex=0;adaptiveCorrect=0;renderAdaptive('discover')}
const applyQs=[['فريق المدرسة سأل الطالبات عن احتياجاتهن من تطبيق جديد.',['التحليل','التصميم','التنفيذ'],'التحليل'],['أصبح التطبيق متاحًا للطالبات وبدأن استخدامه فعليًا.',['الاختبار','التنفيذ','الصيانة'],'التنفيذ'],['بعد شهر ظهر خلل وأصدر الفريق تحديثًا لإصلاحه.',['التقييم','الصيانة','التطوير'],'الصيانة']];
function applyTask(){adaptiveIndex=0;adaptiveCorrect=0;renderAdaptive('apply')}
const innovateQs=[['تريد المدرسة إنشاء نظام لحجز المختبر. ما أفضل بداية للمشروع؟',['برمجة النظام مباشرة','جمع احتياجات المعلمات والطالبات','نشر النظام للمستخدمين'],'جمع احتياجات المعلمات والطالبات'],['بعد تحديد المتطلبات، ما الإجراء الذي يقلل إعادة العمل قبل البرمجة؟',['تصميم الواجهات وآلية العمل','تنفيذ النظام فورًا','البدء بالصيانة'],'تصميم الواجهات وآلية العمل'],['أظهر التقييم أن المستخدمين يواجهون خللًا بعد الإطلاق. ما القرار الأنسب؟',['تجاهل النتائج','العودة للصيانة وإصدار تحديث','إعادة التحليل دون إصلاح'],'العودة للصيانة وإصدار تحديث']];
function innovateTask(){adaptiveIndex=0;adaptiveCorrect=0;renderAdaptive('innovate')}
function renderAdaptive(kind){let data=kind==='discover'?discoverQs:kind==='innovate'?innovateQs:applyQs,q=data[adaptiveIndex],label=kind==='discover'?'🌱 تدريب أكتشف':kind==='innovate'?'💡 تحدي أبتكر':'🎯 مهمة أطبق';S.innerHTML=`${hud()}<h2>${label}</h2><div class='progressbar'><i style='width:${adaptiveIndex/data.length*100}%'></i></div><div class='card q'><span class='pill'>${adaptiveIndex+1} من ${data.length}</span><h3>${q[0]}</h3>${kind==='discover'?'<div class="notice">💡 تلميح: ركزي على الفعل الأساسي في العبارة.</div>':''}${q[1].map(x=>`<button class='option' onclick="answerAdaptive('${kind}','${x.replace(/'/g,"\\'")}')">${x}</button>`).join('')}<div id='adaptiveFb'></div></div>`}
function answerAdaptive(kind,a){let data=kind==='discover'?discoverQs:kind==='innovate'?innovateQs:applyQs,q=data[adaptiveIndex],ok=a===q[2];tone(ok?'good':'bad');let fb=document.querySelector('#adaptiveFb');if(!ok){fb.innerHTML=`<div class='notice'>💡 حاولي مرة أخرى. ${kind==='discover'?'ارجعي إلى النموذج التفاعلي إذا احتجتِ.':'اقرئي الموقف وحددي ما الذي يحدث فعليًا.'}</div>`;return}adaptiveCorrect++;fb.innerHTML=`<div class='feedback'>✓ أحسنتِ، قرار صحيح.</div><button class='cta' onclick="nextAdaptive('${kind}')">${adaptiveIndex+1<data.length?'السؤال التالي ←':'إنهاء المهمة ✨'}</button>`}
function nextAdaptive(kind){let data=kind==='discover'?discoverQs:kind==='innovate'?innovateQs:applyQs;adaptiveIndex++;if(adaptiveIndex<data.length){renderAdaptive(kind);return}let badge=kind==='discover'?'بانية الأساس':kind==='innovate'?'مبتكرة الأنظمة':'محللة المواقف',fresh=!state.badges.includes(badge);if(fresh)award(kind==='innovate'?30:20,badge);celebrate();S.innerHTML=`${hud()}<div class='card game-card' style='text-align:center'><div style='font-size:52px'>${kind==='discover'?'🌱':kind==='innovate'?'💡':'🎯'}</div><h2>أتممتِ مسار «${state.path}»</h2><p>أنجزتِ المهمة المخصصة لمستواك بنجاح.${fresh?` وحصلتِ على شارة <b>«${badge}»</b>.`:''}</p><button class='cta' onclick='gamesHub()'>التالي: مدينة الألعاب 🎮</button></div>`}
