function teacherLogin(){teacherMode=true;S.innerHTML=`<section class='hero'><span class='pill'>👩🏻‍🏫 لوحة المعلمة</span><h2>دخول المعلمة</h2><p>استخدمي حساب المعلمة المسجل في Firebase.</p></section><div class='card profilebox'><input id='te' class='field' type='email' placeholder='البريد الإلكتروني'><input id='tp' class='field' type='password' placeholder='كلمة المرور'><button class='cta' onclick='doTeacherLogin()'>دخول آمن</button><div id='tlfb'></div><button class='cta secondary' onclick='teacherMode=false;home()'>عودة للطالبة</button></div>`}
async function doTeacherLogin(){let e=document.querySelector('#te').value.trim(),p=document.querySelector('#tp').value;try{let r=await auth.signInWithEmailAndPassword(e,p);if(r.user.uid!==TEACHER_UID){await auth.signOut();teacherMode=false;document.querySelector('#tlfb').innerHTML=`<div class='notice'>هذا الحساب غير مخول للوحة المعلمة.</div>`;return}teacherMode=true;teacherDashboard()}catch(err){document.querySelector('#tlfb').innerHTML=`<div class='notice'>تعذر الدخول. تحققي من البريد وكلمة المرور.</div>`}}
let teacherStudents=[],teacherFilter='جميع الفصول',teacherLesson='u1l1';
async function teacherDashboard(filter=teacherFilter){rememberScreen('teacher');teacherMode=true;teacherFilter=filter;S.innerHTML=`<h2>لوحة المعلمة 👩🏻‍🏫</h2><div class='notice'>جاري تحميل بيانات الطالبات…</div>`;try{let q=await db.collection('students').get();teacherStudents=q.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.className||'').localeCompare(b.className||'','ar')||(a.name||'').localeCompare(b.name||'','ar'));renderTeacherDashboard()}catch(e){S.innerHTML=`<h2>لوحة المعلمة</h2><div class='notice'>تعذر قراءة البيانات. تأكدي من نشر قواعد Firestore الجديدة.</div>`}}
function u1(x,key=teacherLesson){return x&&x.course&&x.course[key]?x.course[key]:null}
function teacherLessonMeta(){return teacherLesson==='u1l2'?{label:'الوحدة الأولى · الدرس الثاني',title:'🗓️ بناء وأتمتة خطة المشروع',topics:['برامج إدارة المشروعات','مخطط جانت','التخطيط الزمني','بناء خطة المشروع','المهام الرئيسة والفرعية','ترتيب وأولوية المهام']}:{label:'الوحدة الأولى · الدرس الأول',title:'📋 أساسيات تخطيط المشروعات',topics:['الأساسيات','مثلث إدارة المشروع','تخطيط المشروع','دورة حياة الخطة','مدير المشروع','الخطط المساندة','إدارة التكاليف','تعيين الموارد']}}
function setTeacherLesson(k){teacherLesson=k;renderTeacherDashboard()}
function pct(v){return Number.isFinite(v)?v+'%':'—'}
function renderTeacherDashboard(){
  let meta=teacherLessonMeta();
  let classes=['جميع الفصول','ثالث ثانوي 1','ثالث ثانوي 2','ثالث ثانوي 3'];
  let raw=teacherFilter==='جميع الفصول'?teacherStudents:teacherStudents.filter(x=>x.className===teacherFilter);
  let all=raw.filter(x=>x.accountVersion===2);
  let list=all.filter(x=>u1(x));
  let legacy=raw.length-all.length;
  let avg=a=>a.length?Math.round(a.reduce((s,x)=>s+x,0)/a.length):null;
  let diags=list.map(x=>u1(x).diagnostic).filter(Number.isFinite),posts=list.map(x=>u1(x).post).filter(Number.isFinite);
  let avgDiag=avg(diags),avgPost=avg(posts),mastered=list.filter(x=>u1(x).mastered||u1(x).post>=80).length;
  let delta=avgDiag!=null&&avgPost!=null?avgPost-avgDiag:null;
  S.innerHTML="<div style='display:flex;justify-content:space-between;align-items:center'><h2>لوحة المعلمة 👩🏻‍🏫</h2><button class='ghost logout' onclick='teacherLogout()'>خروج</button></div>"+
  "<div class='tabs teacher-tabs'><button class='tab "+(teacherLesson==='u1l1'?'active':'')+"' onclick=\"setTeacherLesson('u1l1')\">الدرس الأول</button><button class='tab "+(teacherLesson==='u1l2'?'active':'')+"' onclick=\"setTeacherLesson('u1l2')\">الدرس الثاني</button></div>"+
  "<div class='tabs teacher-tabs'>"+classes.map(x=>"<button class='tab "+(x===teacherFilter?'active':'')+"' onclick=\"teacherDashboard('"+x+"')\">"+x+"</button>").join('')+"</div>"+
  "<div class='card parent-card'><span class='pill'>"+meta.label+"</span><h3>"+meta.title+"</h3><div class='teacher-lesson-metrics'><div><small>طالبات بدأن الدرس</small><strong>"+list.length+"</strong></div><div><small>حققن الإتقان</small><strong>"+mastered+"</strong></div><div><small>متوسط التشخيص</small><strong>"+pct(avgDiag)+"</strong></div><div><small>متوسط القياس البعدي</small><strong>"+pct(avgPost)+"</strong></div></div><div class='hud'><span>📈 التحسن: "+(delta==null?'—':(delta>=0?'+':'')+delta+' نقطة')+"</span><span>🏆 الإتقان: "+(posts.length?Math.round(mastered/posts.length*100)+'%':'—')+"</span></div>"+(legacy?"<p class='mini-note'>🧹 تم استبعاد "+legacy+" تسجيلًا قديمًا/تجريبيًا من الإحصاءات حتى لا تختلط بنتائج الحسابات المعتمدة.</p>":"")+"</div>"+
  "<h3 class='section-title'>نتائج الطالبات · "+teacherFilter+"</h3>"+
  (list.length?list.map(x=>{let r=u1(x),weak=Array.isArray(r.weakTopics)?r.weakTopics:[];return "<div class='card student-row' onclick=\"studentDetail('"+x.id+"')\"><h3>"+esc(x.name||'بدون اسم')+"</h3><small>"+esc(x.className||'')+" · مسار "+esc(r.path||'—')+"</small><div class='hud'><span>التشخيص: "+pct(r.diagnostic)+"</span><span>الإتقان: "+pct(r.post)+"</span><span>"+(r.mastered?'🏆 متقنة':'🌱 متابعة')+"</span></div>"+(r.post==null?"<p class='mini-note'>⏳ سيظهر تحليل المحاور بعد إكمال قياس الإتقان.</p>":weak.length?"<p class='mini-note'>"+(r.mastered?'محور يحتاج تعزيزًا: ':'يحتاج دعمًا: ')+weak.map(esc).join(' · ')+"</p>":"<p class='mini-note'>✓ لا توجد محاور تحتاج تعزيزًا مسجلة.</p>")+"</div>"}).join(''):"<div class='notice'>لا توجد نتائج محفوظة لهذا الدرس في هذا الفصل بعد. ستظهر الطالبة هنا بعد إكمال قياس الإتقان.</div>");
}
function studentDetail(id){rememberScreen('teacher');let x=teacherStudents.find(s=>s.id===id);if(!x)return;let r=u1(x),meta=teacherLessonMeta(),topics=meta.topics;let stations=r&&Array.isArray(r.stationMastery)?r.stationMastery:[];let weak=r&&Array.isArray(r.weakTopics)?r.weakTopics:[];S.innerHTML="<button class='ghost' onclick='teacherDashboard()'>← الفصول</button><h2>"+esc(x.name||'بدون اسم')+"</h2><p class='tag'>"+esc(x.className||'')+"</p>"+(r?"<div class='card parent-card'><span class='pill'>"+meta.title+"</span><div class='metric'><div><small>التشخيص</small><strong>"+pct(r.diagnostic)+"</strong></div><div><small>الإتقان</small><strong>"+pct(r.post)+"</strong></div></div><div class='hud'><span>🧭 مسار "+esc(r.path||'—')+"</span><span>"+(r.mastered?'🏆 أتقنت الدرس':'🌱 تحتاج متابعة')+"</span></div><h3>📊 محاور الدرس</h3>"+topics.map((t,i)=>"<div class='notice' style='display:flex;justify-content:space-between;gap:8px'><b>"+(i+1)+". "+t+"</b><span>"+(Number.isFinite(stations[i])?stations[i]+'%':weak.includes(t)?'يحتاج دعمًا':'—')+"</span></div>").join('')+(r.post==null?"<div class='notice'>⏳ تحليل المحاور سيكتمل بعد القياس البعدي.</div>":weak.length?"<div class='notice'><b>"+(r.mastered?'تعزيز مقترح:':'العلاج الموجّه:')+"</b><br>"+weak.map(esc).join(' · ')+"</div>":"<div class='feedback'>✓ لا توجد محاور تحتاج تعزيزًا مسجلة.</div>")+"</div>":"<div class='notice'>لا توجد لهذا الحساب نتائج محفوظة في الدرس المحدد.</div>")+"<div class='card parent-card'><h3>💌 رسالة الرحلة</h3>"+(x.teacherNote?"<div class='teacher-note'><small>"+esc(x.teacherNote.type||'')+"</small><p>"+esc(x.teacherNote.text||'')+"</p></div>":"<div class='notice'>لم تُرسل رسالة لهذه الطالبة بعد.</div>")+"<select id='nt' class='field'><option>🌟 تعزيز</option><option>💡 توجيه</option><option>🌱 تحتاج متابعة</option><option>🏆 تميز</option></select><textarea id='nm' class='field' rows='4' placeholder='اكتبي ملاحظتك للطالبة وولي الأمر…'></textarea><button class='cta' onclick=\"sendTeacherNote('"+id+"')\">إرسال إلى رحلة ابنتي 💌</button><div id='nfb'></div><h3>👪 ملاحظات ولي الأمر</h3>"+((x.parentMessages||[]).length?(x.parentMessages||[]).slice().reverse().map(m=>"<div class='teacher-note'><small>"+esc(m.date||'')+"</small><p>"+esc(m.text||'')+"</p></div>").join(''):"<div class='notice'>لا توجد ملاحظات حتى الآن.</div>")+"<hr style='border:0;border-top:1px solid var(--line);margin:24px 0'><button class='cta secondary danger' onclick=\"deleteStudent('"+id+"')\">🗑️ حذف التسجيل</button><div id='dfb'></div></div>"}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function sendTeacherNote(id){let type=document.querySelector('#nt').value,textv=document.querySelector('#nm').value.trim();if(!textv){document.querySelector('#nfb').innerHTML=`<div class='notice'>اكتبي الرسالة أولًا.</div>`;return}let note={type,text:textv,date:new Date().toLocaleDateString('ar-SA')};try{let x=teacherStudents.find(s=>s.id===id),history=(x&&Array.isArray(x.teacherMessages)?x.teacherMessages:[]);history=[...history,note].slice(-20);await db.collection('students').doc(id).update({teacherNote:note,teacherMessages:history});if(x){x.teacherNote=note;x.teacherMessages=history}document.querySelector('#nfb').innerHTML=`<div class='feedback'>✓ تم إرسال الرسالة وحفظها في سجل التواصل.</div>`;setTimeout(()=>studentDetail(id),650)}catch(e){document.querySelector('#nfb').innerHTML=`<div class='notice'>تعذر إرسال الرسالة.</div>`}}
async function deleteStudent(id){let x=teacherStudents.find(s=>s.id===id);if(!x)return;let ok=confirm('سيتم حذف تسجيل «'+(x.name||'الطالبة')+'» وبيانات رحلتها من لوحة المعلمة. هل أنتِ متأكدة؟');if(!ok)return;try{await db.collection('students').doc(id).delete();teacherStudents=teacherStudents.filter(s=>s.id!==id);teacherDashboard(teacherFilter)}catch(e){let el=document.querySelector('#dfb');if(el)el.innerHTML=`<div class='notice'>تعذر الحذف. يجب السماح للمعلمة بالحذف في قواعد Firestore أولًا.</div>`}}
async function teacherLogout(){teacherMode=false;firebaseUid=null;await auth.signOut();localStorage.removeItem('masari');state={score:null,path:null,post:null,postAnswers:[],attempts:0,points:0,badges:[],gameDone:false,student:null,journeyStep:1,teacherNote:null};home()}
