const qs=[['ما المرحلة التي تبدأ بفهم المشكلة واحتياجات المستخدم؟',['التصميم','التحليل','الاختبار','التنفيذ'],1],['تم تحديد شكل واجهات التطبيق وطريقة الانتقال بينها. ما المرحلة؟',['التحليل','التصميم','الصيانة','التقييم'],1],['تم التأكد من أن جميع وظائف النظام تعمل كما هو مطلوب. ما المرحلة؟',['التطوير','التنفيذ','الاختبار','التوثيق'],2],['ظهر خطأ بعد استخدام النظام ويحتاج إلى إصلاح وتحديث. ما المرحلة؟',['التصميم','التحليل','الصيانة','التوثيق'],2],['ما المرحلة التي تأتي بعد التصميم في المسار الأساسي؟',['التطوير','التقييم','الصيانة','التحليل'],0],['أُجريت مقابلات مع الطالبات لمعرفة احتياجاتهن قبل بناء النظام. ما المرحلة؟',['الاختبار','التحليل','التنفيذ','الصيانة'],1]];let qi=0,correct=0;
function diagnostic(){rememberScreen('diagnostic');qi=0;correct=0;renderQ()}function renderQ(){let q=qs[qi];S.innerHTML=`<h2>الاختبار التشخيصي</h2><div class='progressbar'><i style='width:${qi/qs.length*100}%'></i></div><div class='card q'><span class='pill'>${qi+1} من ${qs.length}</span><h3>${q[0]}</h3>${q[1].map((o,i)=>`<button class='option' onclick='answer(${i})'>${o}</button>`).join('')}</div>`}function answer(i){let ok=i===qs[qi][2];tone(ok?'good':'bad');if(ok)correct++;qi++;if(qi<qs.length)renderQ();else result()}
function result(){tone('good');state.journeyStep=Math.max(state.journeyStep||1,2);let p=Math.round(correct/qs.length*100);state.score=p;state.path=p<50?'أكتشف':p<80?'أطبق':'أبتكر';if(!state.badges.includes('مستكشفة المسار'))award(20,'مستكشفة المسار');save();S.innerHTML=`<div class='card q' style='text-align:center'><h2>أحسنتِ!</h2><p>تم تحديد مسارك بناءً على إجاباتك</p><div class='score' style='--p:${p}%'><strong>${p}%</strong></div><div class='path ${state.path==='أكتشف'?'discover':state.path==='أطبق'?'apply':'innovate'}'><small>مسارك اليوم</small><h3>${state.path}</h3><p>${state.path==='أكتشف'?'نبني الأساس بأمثلة مرئية وتدريب موجه.':state.path==='أطبق'?'نحوّل المعرفة إلى مواقف ومهام تطبيقية.':'نحلل ونتخذ القرار في تحديات متقدمة.'}</p></div><button class='cta' onclick='pathView()'>ابدئي مسارك ←</button></div>`}
function pathView(){rememberScreen('path');state.journeyStep=Math.max(state.journeyStep||1,2);save();let p=state.path||'أطبق',cfg=p==='أكتشف'?{icon:'🌱',intro:'نبني الأساس خطوة بخطوة، مع تلميحات وأمثلة واضحة.',title:'اكتشفي المراحل ثم ثبتي المفهوم',desc:'استكشفي النموذج أولًا، ثم نفّذي تدريب المطابقة الموجّه.',btn:'ابدئي تدريب أكتشف',fn:'discoverTask()'}:p==='أبتكر'?{icon:'💡',intro:'أنتِ جاهزة لمهمة أعلى: حللي موقفًا واقعيًا وابني قرارك.',title:'حللي موقفًا وصممي خطة',desc:'راجعي النموذج عند الحاجة، ثم نفّذي تحدي الابتكار دون تلميحات مباشرة.',btn:'ابدئي تحدي أبتكر',fn:'innovateTask()'}:{icon:'🎯',intro:'حوّلي معرفتك إلى قرار صحيح في مواقف تطبيقية.',title:'طبّقي المراحل على مواقف واقعية',desc:'راجعي النموذج، ثم اختاري المرحلة المناسبة لكل موقف.',btn:'ابدئي مهمة أطبق',fn:'applyTask()'};S.innerHTML=`${hud()}<section class='game-hero'><span class='pill'>🧭 المسار الذكي · ${cfg.icon} ${p}</span><h2>مهمة مسار «${p}»</h2><p>${cfg.intro}</p><div class='level-line'><span>المهمة 2/5</span><div class='level-track'><i style='width:40%'></i></div><span class='xp-pop'>تعلم تكيفي</span></div></section><div class='mission'><div class='mission-head'><div class='mission-icon'>${cfg.icon}</div><div><small>مهمتك المخصصة</small><h3>${cfg.title}</h3></div></div><p>${cfg.desc}</p></div>${model()}<div id='stageDetail' aria-live='polite'><div class='stage-sheet'><div class='stage-head'><div class='stage-icon'>👆</div><div><small>مرجعك التفاعلي</small><h3>اختاري إحدى المراحل</h3></div></div><p>يمكنكِ مراجعة معنى أي مرحلة ومثالها قبل بدء مهمتك.</p></div></div><button class='cta' onclick='${cfg.fn}'>${cfg.btn} ←</button>`}
let adaptiveIndex=0,adaptiveCorrect=0;
const discoverQs=[['نفهم المشكلة واحتياجات المستخدم.',['التحليل','التنفيذ'],'التحليل'],['نرسم شكل الواجهات قبل البرمجة.',['الصيانة','التصميم'],'التصميم'],['نجرب النظام لاكتشاف الأخطاء.',['الاختبار','التوثيق'],'الاختبار']];
function discoverTask(){adaptiveIndex=0;adaptiveCorrect=0;renderAdaptive('discover')}
const applyQs=[['فريق المدرسة سأل الطالبات عن احتياجاتهن من تطبيق جديد.',['التحليل','التصميم','التنفيذ'],'التحليل'],['أصبح التطبيق متاحًا للطالبات وبدأن استخدامه فعليًا.',['الاختبار','التنفيذ','الصيانة'],'التنفيذ'],['بعد شهر ظهر خلل وأصدر الفريق تحديثًا لإصلاحه.',['التقييم','الصيانة','التطوير'],'الصيانة']];
function applyTask(){adaptiveIndex=0;adaptiveCorrect=0;renderAdaptive('apply')}
const innovateQs=[['تريد المدرسة إنشاء نظام لحجز المختبر. ما أفضل بداية للمشروع؟',['برمجة النظام مباشرة','جمع احتياجات المعلمات والطالبات','نشر النظام للمستخدمين'],'جمع احتياجات المعلمات والطالبات'],['بعد تحديد المتطلبات، ما الإجراء الذي يقلل إعادة العمل قبل البرمجة؟',['تصميم الواجهات وآلية العمل','تنفيذ النظام فورًا','البدء بالصيانة'],'تصميم الواجهات وآلية العمل'],['أظهر التقييم أن المستخدمين يواجهون خللًا بعد الإطلاق. ما القرار الأنسب؟',['تجاهل النتائج','العودة للصيانة وإصدار تحديث','إعادة التحليل دون إصلاح'],'العودة للصيانة وإصدار تحديث']];
function innovateTask(){adaptiveIndex=0;adaptiveCorrect=0;renderAdaptive('innovate')}
function renderAdaptive(kind){let data=kind==='discover'?discoverQs:kind==='innovate'?innovateQs:applyQs,q=data[adaptiveIndex],label=kind==='discover'?'🌱 تدريب أكتشف':kind==='innovate'?'💡 تحدي أبتكر':'🎯 مهمة أطبق';S.innerHTML=`${hud()}<h2>${label}</h2><div class='progressbar'><i style='width:${adaptiveIndex/data.length*100}%'></i></div><div class='card q'><span class='pill'>${adaptiveIndex+1} من ${data.length}</span><h3>${q[0]}</h3>${kind==='discover'?'<div class="notice">💡 تلميح: ركزي على الفعل الأساسي في العبارة.</div>':''}${q[1].map(x=>`<button class='option' onclick="answerAdaptive('${kind}','${x.replace(/'/g,"\\'")}')">${x}</button>`).join('')}<div id='adaptiveFb'></div></div>`}
function answerAdaptive(kind,a){let data=kind==='discover'?discoverQs:kind==='innovate'?innovateQs:applyQs,q=data[adaptiveIndex],ok=a===q[2];tone(ok?'good':'bad');let fb=document.querySelector('#adaptiveFb');if(!ok){fb.innerHTML=`<div class='notice'>💡 حاولي مرة أخرى. ${kind==='discover'?'ارجعي إلى النموذج التفاعلي إذا احتجتِ.':'اقرئي الموقف وحددي ما الذي يحدث فعليًا.'}</div>`;return}adaptiveCorrect++;fb.innerHTML=`<div class='feedback'>✓ أحسنتِ، قرار صحيح.</div><button class='cta' onclick="nextAdaptive('${kind}')">${adaptiveIndex+1<data.length?'السؤال التالي ←':'إنهاء المهمة ✨'}</button>`}
function nextAdaptive(kind){let data=kind==='discover'?discoverQs:kind==='innovate'?innovateQs:applyQs;adaptiveIndex++;if(adaptiveIndex<data.length){renderAdaptive(kind);return}let badge=kind==='discover'?'بانية الأساس':kind==='innovate'?'مبتكرة الأنظمة':'محللة المواقف',fresh=!state.badges.includes(badge);if(fresh)award(kind==='innovate'?30:20,badge);celebrate();S.innerHTML=`${hud()}<div class='card game-card' style='text-align:center'><div style='font-size:52px'>${kind==='discover'?'🌱':kind==='innovate'?'💡':'🎯'}</div><h2>أتممتِ مسار «${state.path}»</h2><p>أنجزتِ المهمة المخصصة لمستواك بنجاح.${fresh?` وحصلتِ على شارة <b>«${badge}»</b>.`:''}</p><button class='cta' onclick='gamesHub()'>التالي: مدينة الألعاب 🎮</button></div>`}
function model(){return `<div class='stage3d'><div class='core'>دورة حياة<br>النظام</div>${['التحليل','التصميم','التطوير','الاختبار','التنفيذ','التوثيق','التقييم','الصيانة'].map((x,i)=>`<button class='stage s${i+1}' onclick="stageInfo('${x}')">${x}</button>`).join('')}</div>`}function stageInfo(x){tone('tap');const m={التحليل:['🔎','نفهم المشكلة ونجمع احتياجات المستخدم.','مثال: مقابلة الطالبات لمعرفة ما يحتجنه من التطبيق.'],التصميم:['✏️','نحدد شكل النظام وكيف سيعمل قبل بنائه.','مثال: رسم الواجهات وتحديد طريقة الانتقال بينها.'],التطوير:['🧩','نحوّل التصميم إلى نظام حقيقي ونبني مكوناته.','مثال: برمجة الشاشات والوظائف المطلوبة.'],الاختبار:['🧪','نجرب النظام ونتحقق من عمل وظائفه ونكتشف الأخطاء.','مثال: تجربة زر الدخول والتأكد من عمله كما يجب.'],التنفيذ:['🚀','نطلق النظام ليبدأ المستخدمون باستعماله فعليًا.','مثال: نشر التطبيق وإتاحته للمستخدمين.'],التوثيق:['📝','نسجل معلومات النظام وطريقة استخدامه وصيانته.','مثال: إعداد دليل استخدام واضح للمستخدم.'],التقييم:['📊','نقيس جودة النظام ومدى تحقيقه للأهداف.','مثال: جمع آراء المستخدمين وتحليل النتائج.'],الصيانة:['🛠️','نصلح الأخطاء ونحدّث النظام بعد تشغيله.','مثال: إصدار تحديث لإصلاح خلل ظهر بعد الاستخدام.']};let d=document.querySelector('#stageDetail');if(!d)return;let v=m[x];d.innerHTML=`<div class='stage-sheet'><div class='stage-head'><div class='stage-icon'>${v[0]}</div><div><small>مرحلة</small><h3>${x}</h3></div></div><p>${v[1]}</p><div class='example'>💡 ${v[2]}</div></div>`;d.scrollIntoView({behavior:'smooth',block:'nearest'})}
const postQs=[
['بدأ فريق مشروع بسؤال المستخدمين عن المشكلات التي يواجهونها. ما المرحلة؟',['التصميم','التحليل','التنفيذ','الصيانة'],1],
['حوّل الفريق المتطلبات إلى تصور للواجهات وطريقة عمل النظام. ما المرحلة؟',['التصميم','الاختبار','التقييم','التوثيق'],0],
['بعد بناء النظام جُرّبت وظائفه للتأكد من خلوها من الأخطاء. ما المرحلة؟',['التطوير','الاختبار','التنفيذ','التحليل'],1],
['أصبح النظام متاحًا للمستخدمين وبدأ العمل عليه فعليًا. ما المرحلة؟',['التنفيذ','التوثيق','الصيانة','التصميم'],0],
['بعد فترة من الاستخدام ظهر خلل وأصدر الفريق تحديثًا لإصلاحه. ما المرحلة؟',['الاختبار','التحليل','الصيانة','التطوير'],2]
];let pi=0,pc=0;
function mastery(){rememberScreen('mastery');state.journeyStep=Math.max(state.journeyStep||1,5);save();S.innerHTML=`${hud()}<div class='card q' style='text-align:center'><div style='font-size:50px'>🏆</div><h2>بوابة الإتقان</h2><p>خمسة مواقف قصيرة تقيس فهمك لدورة حياة النظام. جميع المسارات تؤدي إلى هذا القياس نفسه حتى نرى أثر تعلمك بوضوح.</p><div class='notice'>🎯 معيار الإتقان: 80٪ فأعلى</div><button class='cta' onclick='startPost()'>ابدئي القياس البعدي ←</button></div>`}
function startPost(){pi=0;pc=0;state.postAnswers=[];renderPost()}
function renderPost(){let q=postQs[pi];S.innerHTML=`<h2>القياس البعدي</h2><div class='progressbar'><i style='width:${pi/postQs.length*100}%'></i></div><div class='card q'><span class='pill'>${pi+1} من ${postQs.length}</span><h3>${q[0]}</h3>${q[1].map((o,i)=>`<button class='option' onclick='postAnswer(${i})'>${o}</button>`).join('')}</div>`}
function postAnswer(i){let ok=i===postQs[pi][2];tone(ok?'good':'bad');if(ok)pc++;state.postAnswers.push({q:pi,ok});pi++;if(pi<postQs.length)renderPost();else postResult()}
function postResult(){state.post=Math.round(pc/postQs.length*100);state.attempts=(state.attempts||0)+1;save();let mastered=state.post>=80,delta=state.score==null?null:state.post-state.score;if(mastered){if(!state.badges.includes('متقنة الدرس'))award(50,'متقنة الدرس');setTimeout(celebrate,120)}S.innerHTML=`${hud()}<div class='card q' style='text-align:center'><h2>${mastered?'🎉 تم الإتقان':'🌱 نحتاج خطوة علاجية'}</h2><div class='score' style='--p:${state.post}%'><strong>${state.post}%</strong></div><p>المحاولة رقم <b>${state.attempts}</b>${delta==null?'':` · الفرق عن التشخيص <b>${delta>=0?'+':''}${delta}</b> نقطة مئوية`}</p>${mastered?`<div class='feedback'>أحسنتِ، حققتِ معيار الإتقان 80٪ فأعلى. تم حفظ النتيجة في تقدمك.</div><button class='cta' onclick='progress()'>شاهدي أثر تعلمك ←</button>`:`<div class='notice'>لم تصلي إلى 80٪ بعد. سنعرض فقط المفاهيم التي تحتاج إلى تعزيز ثم تعيدين القياس.</div><button class='cta' onclick='remedial()'>ابدئي التدخل العلاجي المخصص ←</button>`}</div>`}
function remedial(){rememberScreen('remedial');let weak=state.postAnswers.filter(x=>!x.ok).map(x=>x.q);const tips=[['🔎 التحليل','اسألي: هل نحن ما زلنا نفهم المشكلة ونجمع احتياجات المستخدم؟ إذن هذه مرحلة التحليل.'],['✏️ التصميم','إذا تحولت المتطلبات إلى شكل للواجهات وطريقة عمل قبل البرمجة، فهذه مرحلة التصميم.'],['🧪 الاختبار','إذا كنا نجرب الوظائف ونبحث عن الأخطاء قبل الاعتماد، فهذه مرحلة الاختبار.'],['🚀 التنفيذ','عندما يصبح النظام متاحًا ويبدأ المستخدمون باستعماله فعليًا، فهذه مرحلة التنفيذ.'],['🛠️ الصيانة','بعد الاستخدام، إصلاح خلل أو إصدار تحديث يعني الصيانة.']];S.innerHTML=`${hud()}<h2>🌱 التدخل العلاجي المخصص</h2><div class='card q'><span class='pill'>بناءً على إجاباتك أنتِ</span><h3>نراجع فقط ${weak.length} ${weak.length===1?'مفهوم يحتاج':'مفاهيم تحتاج'} إلى تعزيز</h3>${weak.map(i=>`<div class='notice'><b>${tips[i][0]}</b><br>${tips[i][1]}</div>`).join('')}<div class='feedback'>بعد المراجعة ستعيدين القياس نفسه للتحقق من وصولك إلى الإتقان.</div><button class='cta' onclick='startPost()'>أنا جاهزة لإعادة القياس ←</button></div>`}
function progress(){rememberScreen('progress');let a=state.score??'—',b=state.post??'—';S.innerHTML=`${hud()}<h2>تقدمي</h2><div class='card parent-card'><h3>دورة حياة النظام</h3><div class='metric'><div><small>البداية</small><strong>${a}${a==='—'?'':'%'}</strong></div><div><small>الحالي</small><strong>${b}${b==='—'?'':'%'}</strong></div></div>${state.post!=null&&state.score!=null?`<div class='notice'>${state.post-state.score>=0?'↑':'↓'} الفرق عن البداية <b>${state.post-state.score>=0?'+':''}${state.post-state.score} نقطة مئوية</b> · عدد محاولات الإتقان: <b>${state.attempts||0}</b></div>`:`<p>أكملي الاختبار التشخيصي والمسار لعرض تقدمك.</p>`}</div><h3 class='section-title'>شاراتي</h3><div class='badge-grid'>${[['🌱','مستكشفة المسار'],['🧩','مهندسة المراحل'],['🗺️','مستكشفة المتاهة'],['🔤','خبيرة المصطلحات'],['🎯','محللة المواقف'],['🏆','متقنة الدرس']].map(b=>`<div class='badge ${state.badges.includes(b[1])?'earned':''}'><b>${b[0]}</b><small>${b[1]}</small></div>`).join('')}</div>`}
